#set_property USER_SLR_ASSIGNMENT SLR0 [get_cells [list top_i/DataPath_xN_0/U0/core_0]]
#set_property USER_SLR_ASSIGNMENT SLR1 [get_cells [list top_i/DataPath_xN_0/U0/core_1]]
#set_property USER_SLR_ASSIGNMENT SLR2 [get_cells [list top_i/DataPath_xN_0/U0/core_2]]
#set_property USER_SLR_ASSIGNMENT SLR3 [get_cells [list top_i/DataPath_xN_0/U0/core_3]]

#set_property USER_SLR_ASSIGNMENT SLR1 [get_cells top_i/xdma_0]

#set_property USER_SLR_ASSIGNMENT SLR0 [get_cells [list top_i/axi_interconnect_0]]
#set_property USER_SLR_ASSIGNMENT SLR1 [get_cells [list top_i/axi_interconnect_1]]
#set_property USER_SLR_ASSIGNMENT SLR2 [get_cells [list top_i/axi_interconnect_2]]
#set_property USER_SLR_ASSIGNMENT SLR3 [get_cells [list top_i/axi_interconnect_3]]

set_false_path -from [get_clocks -of_objects [get_pins top_i/ddr4_0/inst/u_ddr4_infrastructure/gen_mmcme4.u_mmcme_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins top_i/ddr4_3/inst/u_ddr4_infrastructure/gen_mmcme4.u_mmcme_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins top_i/ddr4_0/inst/u_ddr4_infrastructure/gen_mmcme4.u_mmcme_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins top_i/ddr4_1/inst/u_ddr4_infrastructure/gen_mmcme4.u_mmcme_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins top_i/ddr4_3/inst/u_ddr4_infrastructure/gen_mmcme4.u_mmcme_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins top_i/ddr4_2/inst/u_ddr4_infrastructure/gen_mmcme4.u_mmcme_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins top_i/ddr4_1/inst/u_ddr4_infrastructure/gen_mmcme4.u_mmcme_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins top_i/ddr4_2/inst/u_ddr4_infrastructure/gen_mmcme4.u_mmcme_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins top_i/ddr4_2/inst/u_ddr4_infrastructure/gen_mmcme4.u_mmcme_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins top_i/ddr4_1/inst/u_ddr4_infrastructure/gen_mmcme4.u_mmcme_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins top_i/ddr4_1/inst/u_ddr4_infrastructure/gen_mmcme4.u_mmcme_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins top_i/ddr4_3/inst/u_ddr4_infrastructure/gen_mmcme4.u_mmcme_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins top_i/ddr4_1/inst/u_ddr4_infrastructure/gen_mmcme4.u_mmcme_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins top_i/ddr4_0/inst/u_ddr4_infrastructure/gen_mmcme4.u_mmcme_adv_inst/CLKOUT0]]

#create_debug_core u_ila_0 ila
#set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
#set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
#set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
#set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
#set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
#set_property C_INPUT_PIPE_STAGES 4 [get_debug_cores u_ila_0]
#set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
#set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
#set_property port_width 1 [get_debug_ports u_ila_0/clk]
#connect_debug_port u_ila_0/clk [get_nets [list top_i/ddr4_3/inst/u_ddr4_infrastructure/div_clk]]
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
#set_property port_width 6 [get_debug_ports u_ila_0/probe0]
#connect_debug_port u_ila_0/probe0 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_3_core/axi/int_bus_payload_tuser[0]} {top_i/DataPath_xN_0/U0/coreArea_3_core/axi/int_bus_payload_tuser[1]} {top_i/DataPath_xN_0/U0/coreArea_3_core/axi/int_bus_payload_tuser[2]} {top_i/DataPath_xN_0/U0/coreArea_3_core/axi/int_bus_payload_tuser[3]} {top_i/DataPath_xN_0/U0/coreArea_3_core/axi/int_bus_payload_tuser[4]} {top_i/DataPath_xN_0/U0/coreArea_3_core/axi/int_bus_payload_tuser[5]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
#set_property port_width 16 [get_debug_ports u_ila_0/probe1]
#connect_debug_port u_ila_0/probe1 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_3_core/ln/rmsNorm/io_normOut_payload[0]} {top_i/DataPath_xN_0/U0/coreArea_3_core/ln/rmsNorm/io_normOut_payload[1]} {top_i/DataPath_xN_0/U0/coreArea_3_core/ln/rmsNorm/io_normOut_payload[2]} {top_i/DataPath_xN_0/U0/coreArea_3_core/ln/rmsNorm/io_normOut_payload[3]} {top_i/DataPath_xN_0/U0/coreArea_3_core/ln/rmsNorm/io_normOut_payload[4]} {top_i/DataPath_xN_0/U0/coreArea_3_core/ln/rmsNorm/io_normOut_payload[5]} {top_i/DataPath_xN_0/U0/coreArea_3_core/ln/rmsNorm/io_normOut_payload[6]} {top_i/DataPath_xN_0/U0/coreArea_3_core/ln/rmsNorm/io_normOut_payload[7]} {top_i/DataPath_xN_0/U0/coreArea_3_core/ln/rmsNorm/io_normOut_payload[8]} {top_i/DataPath_xN_0/U0/coreArea_3_core/ln/rmsNorm/io_normOut_payload[9]} {top_i/DataPath_xN_0/U0/coreArea_3_core/ln/rmsNorm/io_normOut_payload[10]} {top_i/DataPath_xN_0/U0/coreArea_3_core/ln/rmsNorm/io_normOut_payload[11]} {top_i/DataPath_xN_0/U0/coreArea_3_core/ln/rmsNorm/io_normOut_payload[12]} {top_i/DataPath_xN_0/U0/coreArea_3_core/ln/rmsNorm/io_normOut_payload[13]} {top_i/DataPath_xN_0/U0/coreArea_3_core/ln/rmsNorm/io_normOut_payload[14]} {top_i/DataPath_xN_0/U0/coreArea_3_core/ln/rmsNorm/io_normOut_payload[15]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
#set_property port_width 6 [get_debug_ports u_ila_0/probe2]
#connect_debug_port u_ila_0/probe2 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tuser[0]} {top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tuser[1]} {top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tuser[2]} {top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tuser[3]} {top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tuser[4]} {top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tuser[5]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
#set_property port_width 16 [get_debug_ports u_ila_0/probe3]
#connect_debug_port u_ila_0/probe3 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tdata[0]} {top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tdata[1]} {top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tdata[2]} {top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tdata[3]} {top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tdata[4]} {top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tdata[5]} {top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tdata[6]} {top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tdata[7]} {top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tdata[8]} {top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tdata[9]} {top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tdata[10]} {top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tdata[11]} {top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tdata[12]} {top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tdata[13]} {top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tdata[14]} {top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tdata[15]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
#set_property port_width 10 [get_debug_ports u_ila_0/probe4]
#connect_debug_port u_ila_0/probe4 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_3_core/stateGen_4/status_token[0]} {top_i/DataPath_xN_0/U0/coreArea_3_core/stateGen_4/status_token[1]} {top_i/DataPath_xN_0/U0/coreArea_3_core/stateGen_4/status_token[2]} {top_i/DataPath_xN_0/U0/coreArea_3_core/stateGen_4/status_token[3]} {top_i/DataPath_xN_0/U0/coreArea_3_core/stateGen_4/status_token[4]} {top_i/DataPath_xN_0/U0/coreArea_3_core/stateGen_4/status_token[5]} {top_i/DataPath_xN_0/U0/coreArea_3_core/stateGen_4/status_token[6]} {top_i/DataPath_xN_0/U0/coreArea_3_core/stateGen_4/status_token[7]} {top_i/DataPath_xN_0/U0/coreArea_3_core/stateGen_4/status_token[8]} {top_i/DataPath_xN_0/U0/coreArea_3_core/stateGen_4/status_token[9]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
#set_property port_width 5 [get_debug_ports u_ila_0/probe5]
#connect_debug_port u_ila_0/probe5 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_3_core/stateGen_4/status_layerCnt[0]} {top_i/DataPath_xN_0/U0/coreArea_3_core/stateGen_4/status_layerCnt[1]} {top_i/DataPath_xN_0/U0/coreArea_3_core/stateGen_4/status_layerCnt[2]} {top_i/DataPath_xN_0/U0/coreArea_3_core/stateGen_4/status_layerCnt[3]} {top_i/DataPath_xN_0/U0/coreArea_3_core/stateGen_4/status_layerCnt[4]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
#set_property port_width 1 [get_debug_ports u_ila_0/probe6]
#connect_debug_port u_ila_0/probe6 [get_nets [list top_i/DataPath_xN_0/U0/coreArea_3_core/ln/rmsNorm/io_normOut_valid]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
#set_property port_width 1 [get_debug_ports u_ila_0/probe7]
#connect_debug_port u_ila_0/probe7 [get_nets [list top_i/DataPath_xN_0/U0/coreArea_3_core/engine/scalarOut_tvalid]]
#create_debug_core u_ila_1 ila
#set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
#set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
#set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
#set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_1]
#set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
#set_property C_INPUT_PIPE_STAGES 4 [get_debug_cores u_ila_1]
#set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
#set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
#set_property port_width 1 [get_debug_ports u_ila_1/clk]
#connect_debug_port u_ila_1/clk [get_nets [list top_i/ddr4_2/inst/u_ddr4_infrastructure/div_clk]]
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
#set_property port_width 16 [get_debug_ports u_ila_1/probe0]
#connect_debug_port u_ila_1/probe0 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tdata[0]} {top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tdata[1]} {top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tdata[2]} {top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tdata[3]} {top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tdata[4]} {top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tdata[5]} {top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tdata[6]} {top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tdata[7]} {top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tdata[8]} {top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tdata[9]} {top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tdata[10]} {top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tdata[11]} {top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tdata[12]} {top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tdata[13]} {top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tdata[14]} {top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tdata[15]}]]
#create_debug_port u_ila_1 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
#set_property port_width 6 [get_debug_ports u_ila_1/probe1]
#connect_debug_port u_ila_1/probe1 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tuser[0]} {top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tuser[1]} {top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tuser[2]} {top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tuser[3]} {top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tuser[4]} {top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tuser[5]}]]
#create_debug_port u_ila_1 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
#set_property port_width 5 [get_debug_ports u_ila_1/probe2]
#connect_debug_port u_ila_1/probe2 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_2_core/stateGen_4/status_layerCnt[0]} {top_i/DataPath_xN_0/U0/coreArea_2_core/stateGen_4/status_layerCnt[1]} {top_i/DataPath_xN_0/U0/coreArea_2_core/stateGen_4/status_layerCnt[2]} {top_i/DataPath_xN_0/U0/coreArea_2_core/stateGen_4/status_layerCnt[3]} {top_i/DataPath_xN_0/U0/coreArea_2_core/stateGen_4/status_layerCnt[4]}]]
#create_debug_port u_ila_1 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
#set_property port_width 10 [get_debug_ports u_ila_1/probe3]
#connect_debug_port u_ila_1/probe3 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_2_core/stateGen_4/status_token[0]} {top_i/DataPath_xN_0/U0/coreArea_2_core/stateGen_4/status_token[1]} {top_i/DataPath_xN_0/U0/coreArea_2_core/stateGen_4/status_token[2]} {top_i/DataPath_xN_0/U0/coreArea_2_core/stateGen_4/status_token[3]} {top_i/DataPath_xN_0/U0/coreArea_2_core/stateGen_4/status_token[4]} {top_i/DataPath_xN_0/U0/coreArea_2_core/stateGen_4/status_token[5]} {top_i/DataPath_xN_0/U0/coreArea_2_core/stateGen_4/status_token[6]} {top_i/DataPath_xN_0/U0/coreArea_2_core/stateGen_4/status_token[7]} {top_i/DataPath_xN_0/U0/coreArea_2_core/stateGen_4/status_token[8]} {top_i/DataPath_xN_0/U0/coreArea_2_core/stateGen_4/status_token[9]}]]
#create_debug_port u_ila_1 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
#set_property port_width 6 [get_debug_ports u_ila_1/probe4]
#connect_debug_port u_ila_1/probe4 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_2_core/axi/int_bus_payload_tuser[0]} {top_i/DataPath_xN_0/U0/coreArea_2_core/axi/int_bus_payload_tuser[1]} {top_i/DataPath_xN_0/U0/coreArea_2_core/axi/int_bus_payload_tuser[2]} {top_i/DataPath_xN_0/U0/coreArea_2_core/axi/int_bus_payload_tuser[3]} {top_i/DataPath_xN_0/U0/coreArea_2_core/axi/int_bus_payload_tuser[4]} {top_i/DataPath_xN_0/U0/coreArea_2_core/axi/int_bus_payload_tuser[5]}]]
#create_debug_port u_ila_1 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
#set_property port_width 16 [get_debug_ports u_ila_1/probe5]
#connect_debug_port u_ila_1/probe5 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_2_core/ln/rmsNorm/io_normOut_payload[0]} {top_i/DataPath_xN_0/U0/coreArea_2_core/ln/rmsNorm/io_normOut_payload[1]} {top_i/DataPath_xN_0/U0/coreArea_2_core/ln/rmsNorm/io_normOut_payload[2]} {top_i/DataPath_xN_0/U0/coreArea_2_core/ln/rmsNorm/io_normOut_payload[3]} {top_i/DataPath_xN_0/U0/coreArea_2_core/ln/rmsNorm/io_normOut_payload[4]} {top_i/DataPath_xN_0/U0/coreArea_2_core/ln/rmsNorm/io_normOut_payload[5]} {top_i/DataPath_xN_0/U0/coreArea_2_core/ln/rmsNorm/io_normOut_payload[6]} {top_i/DataPath_xN_0/U0/coreArea_2_core/ln/rmsNorm/io_normOut_payload[7]} {top_i/DataPath_xN_0/U0/coreArea_2_core/ln/rmsNorm/io_normOut_payload[8]} {top_i/DataPath_xN_0/U0/coreArea_2_core/ln/rmsNorm/io_normOut_payload[9]} {top_i/DataPath_xN_0/U0/coreArea_2_core/ln/rmsNorm/io_normOut_payload[10]} {top_i/DataPath_xN_0/U0/coreArea_2_core/ln/rmsNorm/io_normOut_payload[11]} {top_i/DataPath_xN_0/U0/coreArea_2_core/ln/rmsNorm/io_normOut_payload[12]} {top_i/DataPath_xN_0/U0/coreArea_2_core/ln/rmsNorm/io_normOut_payload[13]} {top_i/DataPath_xN_0/U0/coreArea_2_core/ln/rmsNorm/io_normOut_payload[14]} {top_i/DataPath_xN_0/U0/coreArea_2_core/ln/rmsNorm/io_normOut_payload[15]}]]
#create_debug_port u_ila_1 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
#set_property port_width 1 [get_debug_ports u_ila_1/probe6]
#connect_debug_port u_ila_1/probe6 [get_nets [list top_i/DataPath_xN_0/U0/coreArea_2_core/ln/rmsNorm/io_normOut_valid]]
#create_debug_port u_ila_1 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
#set_property port_width 1 [get_debug_ports u_ila_1/probe7]
#connect_debug_port u_ila_1/probe7 [get_nets [list top_i/DataPath_xN_0/U0/coreArea_2_core/engine/scalarOut_tvalid]]
#create_debug_core u_ila_2 ila
#set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
#set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_2]
#set_property C_ADV_TRIGGER false [get_debug_cores u_ila_2]
#set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_2]
#set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_2]
#set_property C_INPUT_PIPE_STAGES 4 [get_debug_cores u_ila_2]
#set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
#set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
#set_property port_width 1 [get_debug_ports u_ila_2/clk]
#connect_debug_port u_ila_2/clk [get_nets [list top_i/ddr4_1/inst/u_ddr4_infrastructure/div_clk]]
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
#set_property port_width 6 [get_debug_ports u_ila_2/probe0]
#connect_debug_port u_ila_2/probe0 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_1_core/axi/int_bus_payload_tuser[0]} {top_i/DataPath_xN_0/U0/coreArea_1_core/axi/int_bus_payload_tuser[1]} {top_i/DataPath_xN_0/U0/coreArea_1_core/axi/int_bus_payload_tuser[2]} {top_i/DataPath_xN_0/U0/coreArea_1_core/axi/int_bus_payload_tuser[3]} {top_i/DataPath_xN_0/U0/coreArea_1_core/axi/int_bus_payload_tuser[4]} {top_i/DataPath_xN_0/U0/coreArea_1_core/axi/int_bus_payload_tuser[5]}]]
#create_debug_port u_ila_2 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe1]
#set_property port_width 6 [get_debug_ports u_ila_2/probe1]
#connect_debug_port u_ila_2/probe1 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tuser[0]} {top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tuser[1]} {top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tuser[2]} {top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tuser[3]} {top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tuser[4]} {top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tuser[5]}]]
#create_debug_port u_ila_2 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe2]
#set_property port_width 16 [get_debug_ports u_ila_2/probe2]
#connect_debug_port u_ila_2/probe2 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tdata[0]} {top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tdata[1]} {top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tdata[2]} {top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tdata[3]} {top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tdata[4]} {top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tdata[5]} {top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tdata[6]} {top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tdata[7]} {top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tdata[8]} {top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tdata[9]} {top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tdata[10]} {top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tdata[11]} {top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tdata[12]} {top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tdata[13]} {top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tdata[14]} {top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tdata[15]}]]
#create_debug_port u_ila_2 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe3]
#set_property port_width 16 [get_debug_ports u_ila_2/probe3]
#connect_debug_port u_ila_2/probe3 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_1_core/ln/rmsNorm/io_normOut_payload[0]} {top_i/DataPath_xN_0/U0/coreArea_1_core/ln/rmsNorm/io_normOut_payload[1]} {top_i/DataPath_xN_0/U0/coreArea_1_core/ln/rmsNorm/io_normOut_payload[2]} {top_i/DataPath_xN_0/U0/coreArea_1_core/ln/rmsNorm/io_normOut_payload[3]} {top_i/DataPath_xN_0/U0/coreArea_1_core/ln/rmsNorm/io_normOut_payload[4]} {top_i/DataPath_xN_0/U0/coreArea_1_core/ln/rmsNorm/io_normOut_payload[5]} {top_i/DataPath_xN_0/U0/coreArea_1_core/ln/rmsNorm/io_normOut_payload[6]} {top_i/DataPath_xN_0/U0/coreArea_1_core/ln/rmsNorm/io_normOut_payload[7]} {top_i/DataPath_xN_0/U0/coreArea_1_core/ln/rmsNorm/io_normOut_payload[8]} {top_i/DataPath_xN_0/U0/coreArea_1_core/ln/rmsNorm/io_normOut_payload[9]} {top_i/DataPath_xN_0/U0/coreArea_1_core/ln/rmsNorm/io_normOut_payload[10]} {top_i/DataPath_xN_0/U0/coreArea_1_core/ln/rmsNorm/io_normOut_payload[11]} {top_i/DataPath_xN_0/U0/coreArea_1_core/ln/rmsNorm/io_normOut_payload[12]} {top_i/DataPath_xN_0/U0/coreArea_1_core/ln/rmsNorm/io_normOut_payload[13]} {top_i/DataPath_xN_0/U0/coreArea_1_core/ln/rmsNorm/io_normOut_payload[14]} {top_i/DataPath_xN_0/U0/coreArea_1_core/ln/rmsNorm/io_normOut_payload[15]}]]
#create_debug_port u_ila_2 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe4]
#set_property port_width 5 [get_debug_ports u_ila_2/probe4]
#connect_debug_port u_ila_2/probe4 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_1_core/stateGen_4/status_layerCnt[0]} {top_i/DataPath_xN_0/U0/coreArea_1_core/stateGen_4/status_layerCnt[1]} {top_i/DataPath_xN_0/U0/coreArea_1_core/stateGen_4/status_layerCnt[2]} {top_i/DataPath_xN_0/U0/coreArea_1_core/stateGen_4/status_layerCnt[3]} {top_i/DataPath_xN_0/U0/coreArea_1_core/stateGen_4/status_layerCnt[4]}]]
#create_debug_port u_ila_2 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe5]
#set_property port_width 10 [get_debug_ports u_ila_2/probe5]
#connect_debug_port u_ila_2/probe5 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_1_core/stateGen_4/status_token[0]} {top_i/DataPath_xN_0/U0/coreArea_1_core/stateGen_4/status_token[1]} {top_i/DataPath_xN_0/U0/coreArea_1_core/stateGen_4/status_token[2]} {top_i/DataPath_xN_0/U0/coreArea_1_core/stateGen_4/status_token[3]} {top_i/DataPath_xN_0/U0/coreArea_1_core/stateGen_4/status_token[4]} {top_i/DataPath_xN_0/U0/coreArea_1_core/stateGen_4/status_token[5]} {top_i/DataPath_xN_0/U0/coreArea_1_core/stateGen_4/status_token[6]} {top_i/DataPath_xN_0/U0/coreArea_1_core/stateGen_4/status_token[7]} {top_i/DataPath_xN_0/U0/coreArea_1_core/stateGen_4/status_token[8]} {top_i/DataPath_xN_0/U0/coreArea_1_core/stateGen_4/status_token[9]}]]
#create_debug_port u_ila_2 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe6]
#set_property port_width 1 [get_debug_ports u_ila_2/probe6]
#connect_debug_port u_ila_2/probe6 [get_nets [list top_i/DataPath_xN_0/U0/coreArea_1_core/ln/rmsNorm/io_normOut_valid]]
#create_debug_port u_ila_2 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe7]
#set_property port_width 1 [get_debug_ports u_ila_2/probe7]
#connect_debug_port u_ila_2/probe7 [get_nets [list top_i/DataPath_xN_0/U0/coreArea_1_core/engine/scalarOut_tvalid]]
#create_debug_core u_ila_3 ila
#set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_3]
#set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_3]
#set_property C_ADV_TRIGGER false [get_debug_cores u_ila_3]
#set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_3]
#set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_3]
#set_property C_INPUT_PIPE_STAGES 4 [get_debug_cores u_ila_3]
#set_property C_TRIGIN_EN false [get_debug_cores u_ila_3]
#set_property C_TRIGOUT_EN false [get_debug_cores u_ila_3]
#set_property port_width 1 [get_debug_ports u_ila_3/clk]
#connect_debug_port u_ila_3/clk [get_nets [list top_i/ddr4_0/inst/u_ddr4_infrastructure/div_clk]]
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe0]
#set_property port_width 16 [get_debug_ports u_ila_3/probe0]
#connect_debug_port u_ila_3/probe0 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_0_core/ln/rmsNorm/io_normOut_payload[0]} {top_i/DataPath_xN_0/U0/coreArea_0_core/ln/rmsNorm/io_normOut_payload[1]} {top_i/DataPath_xN_0/U0/coreArea_0_core/ln/rmsNorm/io_normOut_payload[2]} {top_i/DataPath_xN_0/U0/coreArea_0_core/ln/rmsNorm/io_normOut_payload[3]} {top_i/DataPath_xN_0/U0/coreArea_0_core/ln/rmsNorm/io_normOut_payload[4]} {top_i/DataPath_xN_0/U0/coreArea_0_core/ln/rmsNorm/io_normOut_payload[5]} {top_i/DataPath_xN_0/U0/coreArea_0_core/ln/rmsNorm/io_normOut_payload[6]} {top_i/DataPath_xN_0/U0/coreArea_0_core/ln/rmsNorm/io_normOut_payload[7]} {top_i/DataPath_xN_0/U0/coreArea_0_core/ln/rmsNorm/io_normOut_payload[8]} {top_i/DataPath_xN_0/U0/coreArea_0_core/ln/rmsNorm/io_normOut_payload[9]} {top_i/DataPath_xN_0/U0/coreArea_0_core/ln/rmsNorm/io_normOut_payload[10]} {top_i/DataPath_xN_0/U0/coreArea_0_core/ln/rmsNorm/io_normOut_payload[11]} {top_i/DataPath_xN_0/U0/coreArea_0_core/ln/rmsNorm/io_normOut_payload[12]} {top_i/DataPath_xN_0/U0/coreArea_0_core/ln/rmsNorm/io_normOut_payload[13]} {top_i/DataPath_xN_0/U0/coreArea_0_core/ln/rmsNorm/io_normOut_payload[14]} {top_i/DataPath_xN_0/U0/coreArea_0_core/ln/rmsNorm/io_normOut_payload[15]}]]
#create_debug_port u_ila_3 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe1]
#set_property port_width 6 [get_debug_ports u_ila_3/probe1]
#connect_debug_port u_ila_3/probe1 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_0_core/axi/int_bus_payload_tuser[0]} {top_i/DataPath_xN_0/U0/coreArea_0_core/axi/int_bus_payload_tuser[1]} {top_i/DataPath_xN_0/U0/coreArea_0_core/axi/int_bus_payload_tuser[2]} {top_i/DataPath_xN_0/U0/coreArea_0_core/axi/int_bus_payload_tuser[3]} {top_i/DataPath_xN_0/U0/coreArea_0_core/axi/int_bus_payload_tuser[4]} {top_i/DataPath_xN_0/U0/coreArea_0_core/axi/int_bus_payload_tuser[5]}]]
#create_debug_port u_ila_3 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe2]
#set_property port_width 16 [get_debug_ports u_ila_3/probe2]
#connect_debug_port u_ila_3/probe2 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tdata[0]} {top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tdata[1]} {top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tdata[2]} {top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tdata[3]} {top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tdata[4]} {top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tdata[5]} {top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tdata[6]} {top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tdata[7]} {top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tdata[8]} {top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tdata[9]} {top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tdata[10]} {top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tdata[11]} {top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tdata[12]} {top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tdata[13]} {top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tdata[14]} {top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tdata[15]}]]
#create_debug_port u_ila_3 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe3]
#set_property port_width 6 [get_debug_ports u_ila_3/probe3]
#connect_debug_port u_ila_3/probe3 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tuser[0]} {top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tuser[1]} {top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tuser[2]} {top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tuser[3]} {top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tuser[4]} {top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tuser[5]}]]
#create_debug_port u_ila_3 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe4]
#set_property port_width 10 [get_debug_ports u_ila_3/probe4]
#connect_debug_port u_ila_3/probe4 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_0_core/stateGen_4/status_token[0]} {top_i/DataPath_xN_0/U0/coreArea_0_core/stateGen_4/status_token[1]} {top_i/DataPath_xN_0/U0/coreArea_0_core/stateGen_4/status_token[2]} {top_i/DataPath_xN_0/U0/coreArea_0_core/stateGen_4/status_token[3]} {top_i/DataPath_xN_0/U0/coreArea_0_core/stateGen_4/status_token[4]} {top_i/DataPath_xN_0/U0/coreArea_0_core/stateGen_4/status_token[5]} {top_i/DataPath_xN_0/U0/coreArea_0_core/stateGen_4/status_token[6]} {top_i/DataPath_xN_0/U0/coreArea_0_core/stateGen_4/status_token[7]} {top_i/DataPath_xN_0/U0/coreArea_0_core/stateGen_4/status_token[8]} {top_i/DataPath_xN_0/U0/coreArea_0_core/stateGen_4/status_token[9]}]]
#create_debug_port u_ila_3 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe5]
#set_property port_width 5 [get_debug_ports u_ila_3/probe5]
#connect_debug_port u_ila_3/probe5 [get_nets [list {top_i/DataPath_xN_0/U0/coreArea_0_core/stateGen_4/status_layerCnt[0]} {top_i/DataPath_xN_0/U0/coreArea_0_core/stateGen_4/status_layerCnt[1]} {top_i/DataPath_xN_0/U0/coreArea_0_core/stateGen_4/status_layerCnt[2]} {top_i/DataPath_xN_0/U0/coreArea_0_core/stateGen_4/status_layerCnt[3]} {top_i/DataPath_xN_0/U0/coreArea_0_core/stateGen_4/status_layerCnt[4]}]]
#create_debug_port u_ila_3 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe6]
#set_property port_width 1 [get_debug_ports u_ila_3/probe6]
#connect_debug_port u_ila_3/probe6 [get_nets [list top_i/DataPath_xN_0/U0/coreArea_0_core/ln/rmsNorm/io_normOut_valid]]
#create_debug_port u_ila_3 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_3/probe7]
#set_property port_width 1 [get_debug_ports u_ila_3/probe7]
#connect_debug_port u_ila_3/probe7 [get_nets [list top_i/DataPath_xN_0/U0/coreArea_0_core/engine/scalarOut_tvalid]]
#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets clk]
